name: Android CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: AMGQuizApp.zip_unzipped
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          build-root-directory: AMGQuizApp.zip_unzipped
      - name: Build Debug APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AMGQuizApp-debug-apk
          path: AMGQuizApp.zip_unzipped/app/build/outputs/apk/debug/app-debug.apk
